### PR TITLE
Feature/developer toolkit

### PR DESCRIPTION
**Pull request by xaun**
dist files are commited, with updated structure, please review and make sure it will be ok before merge.

### CODE REVIEW

**Comment by cesar-tonnoir** [comment]
Would be cool to have a warning when you don't have valid credentials set in configuration, instead of having the dashboard loading forever

**Comment by xaun** [comment]
@cesar-tonnoir I have added a console error log for when credentials are missing. Although in the near future I would like to add a little modal, and stop the dashboard loading.

**Comment by cesar-tonnoir** [comment]
> need to tag v1.2 and update all enterprise projects with new routes configuration

**Comment by cesar-tonnoir** [comment]
@xaun: need a last back-merge on your branch (tried to do it and push to your branch, but apparently i don't have the rights anymore)

**Pull request merged**
