### PR TITLE
Add workspace stubbing

### PR DESCRIPTION
**Pull request by alachaum**

### CODE REVIEW

**Comment by alachaum** [comment]
@cesar-tonnoir or @xaun please review and let me know.

**Comment by xaun** [comment]
@alachaum looks good - thanks for speccing the #update method =D, I think we should merge this PR in with a WIP branch of mine that adds a developer provider service. So instead of commenting / uncommenting a full dashboard stub in the index.js, we can provide these sort of things to the service

See here for an example: 
https://github.com/xaun/impac-angular/commit/8a2725f83ef9befbf2728263642301f7f95c1b96

@cesar-tonnoir

**Comment by alachaum** [comment]
@xaun works for me - as long as we can get that done soon.

**Comment by xaun** [comment]
Hi @alachaum this is merged with #126 , please review :beers:

**Comment by cesar-tonnoir** [comment]
@alachaum #126 merged to v1.2
Will be deployed today to Mno PROD

**Pull request closed without merging**
