### PR TITLE
Feature/kpi custom template

### PR DESCRIPTION
**Pull request by leomao10**
Hi There, 

In PwC Enterprise, Nigel want to change the look and feel for kpis-bar, and I found that it is really hard to adjust the look and feel without changing the Html template. 

And I found that kpis-bar does not allow custom template. So I re-used custom template function in `dashboard-selector`,  and make kpis-bar accept custom template.

Please let me know how you think

Thanks

Leo Liang

### CODE REVIEW

**Comment by cesar-tonnoir** [comment]
Hi @leomao10,

I don't know if the information reached you (sorry for the delay if it's not the case), so I'll respond directly into your pull request.

Actually, the kpis bar is used only in Next project so far, so if the UI is to be improved, I'd prefer add the improvements directly to the main project rather than adding it as a customization.
Generally speaking, if you want to propose UI, design or architectural improvements to Impac!, I think we should discuss it before you start working on it. Improvements are very welcome, but first, we have to make sure that it matches the project's principles, and that it will fit with all the other sites that are using the library.

For this particular case (kpis bar), could you please send me screenshots of your improvements?

Thanks

**Comment by leomao10** [comment]
Hi @cesar-tonnoir 

Thanks for your email, the information must drop somewhere in the middle, but good to get a message from you.

I thought it might be easier for you to add it as customization, as it may not fix others sites. But I am OK to add the improvements to the main project if that is your preference.

Here are the screenshots for what our designer purpose:
screenshot_2016-02-25_12 16 09

Let me know how you think and we can discuss about it

Cheers

Leo Liang

**Comment by cesar-tonnoir** [comment]
Hi @leomao10,
I appreciate the intention ;-).

Yes, I have seen this mock-up already a few months ago. The difficulty in changing the current design is that the kpis are completely dynamic (all using the same template) => it's a little bit more difficult to design it in the beginning, but far easier then when we want to add new kpis.

We are currently working on a general rework of the KPIs in the team (mostly back-end so far): if you have to work on it as well for the front, I think we should meet as soon as possible and make sure everybody is working in the same direction.

I will see with Johan and Nigel when we could organize that.

Cheers
Cesar.

**Comment by leomao10** [comment]
Yup, I just receive the invitation. Will chat with you on Tue :)

Cheers

Leo Liang

On Wed, Apr 27, 2016 at 3:38 PM, Cesar Tonnoir <notifications@github.com>
wrote:

> Hi @leomao10 <https://github.com/leomao10>,
> I appreciate the intention ;-).
>
> Yes, I have seen this mock-up already a few months ago. The difficulty in
> changing the current design is that the kpis are completely dynamic (all
> using the same template) => it's a little bit more difficult to design it
> in the beginning, but far easier then when we want to add new kpis.
>
> We are currently working on a general rework of the KPIs in the team
> (mostly back-end so far): if you have to work on it as well for the front,
> I think we should meet as soon as possible and make sure everybody is
> working in the same direction.
>
> I will see with Johan and Nigel when we could organize that.
>
> Cheers
> Cesar.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/maestrano/impac-angular/pull/139#issuecomment-214976612>
>



-- 
Cheers

Leo Liang

**Comment by cesar-tonnoir** [comment]
Hi @leomao10 following our discussion, I'm closing this PR for the moment. Tell me when you're ready to  submit your changes on KPIs.
Also: could you please keep your build files (/dist) out of the PR? It will prevent you from having conflicts.
Thanks!

**Comment by leomao10** [comment]
Yup, will do that in next PR. Thanks :)

On Thu, May 5, 2016 at 8:15 PM, Cesar Tonnoir <notifications@github.com>
wrote:

> Hi @leomao10 <https://github.com/leomao10> following our discussion, I'm
> closing this PR for the moment. Tell me when you're ready to submit your
> changes on KPIs.
> Also: could you please keep your build files (/dist) out of the PR? It
> will prevent you from having conflicts.
> Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/maestrano/impac-angular/pull/139#issuecomment-217338771>
>



-- 
Cheers

Leo Liang

**Pull request closed without merging**
